apiVersion: api.tsb.tetrate.io/v2
kind: TenantSetting
metadata:
  displayName: default-setting
  name: default-setting
  organization: coreos-0-org
  tenant: wealth-mgmt
spec:
  defaultSecuritySetting:
    displayName: default-security
    authenticationSettings:
      trafficMode: REQUIRED
    authorization:
      mode: RULES
      rules:
        denyAll: true
    

