---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  labels:
    app: frontend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  labels:
    app: backend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
subjects:
- kind: ServiceAccount
  name: backend
  apiGroup: ""
- kind: ServiceAccount
  name: frontend
  apiGroup: ""
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io