---
apiVersion: install.tetrate.io/v1alpha1
kind: IngressGateway
metadata:
  name: credit-gateway
spec:
  kubeSpec:
    service:
      type: LoadBalancer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontend
spec:
  secretName: frontend-cert
  issuerRef:
    name: letsencrypt-dns-cluster-issuer
    kind: ClusterIssuer
