---
apiVersion: install.tetrate.io/v1alpha1
kind: IngressGateway
metadata:
  name: quotes-ingress
spec:
  kubeSpec:
    service:
      type: LoadBalancer
      annotations:
        "external-dns.alpha.kubernetes.io/hostname": "quotes.aws-east.yosemite.cx.tetrate.info."
        "external-dns.alpha.kubernetes.io/alias": "true"
        "external-dns.alpha.kubernetes.io/set-identifier": "aws-east"
        "external-dns.alpha.kubernetes.io/aws-region": "us-east-2"
        "service.beta.kubernetes.io/aws-load-balancer-type": "nlb"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: quotes-cert
spec:
  secretName: quotes-cert
  issuerRef:
    name: letsencrypt-dns-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
  - quotes.aws-east.yosemite.cx.tetrate.info