---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quotes
      version: v1
  template:
    metadata:
      name: quotes
      labels:
        app: quotes
        version: v1
    spec:
      serviceAccountName: quotes-sa
      containers:
        - image: gcr.io/abz-perm/quotes:v1
          name: quotes-service
          imagePullPolicy: Always
          # resources:
          #   limits:
          #     cpu: 500m
          #     memory: 512Mi
          #   requests:
          #     cpu: 100m
          #     memory: 128Mi
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080