---
apiVersion: install.tetrate.io/v1alpha1
kind: IngressGateway
metadata:
  name: quotes-ingress
spec:
  kubeSpec:
    service:
      type: LoadBalancer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: quotes-cert
spec:
  secretName: quotes-cert
  issuerRef:
    name: selfsigned-issuer-control-plane
    kind: ClusterIssuer
  dnsNames:
  - quotes.rh-demo.cx.tetrate.info