# ---
# apiVersion: install.tetrate.io/v1alpha1
# kind: IngressGateway
# metadata:
#   name: fraud-gateway
# spec:
#   kubeSpec:
#     service:
#       annotations:
#         "external-dns.alpha.kubernetes.io/hostname": "fraud.aws-east-dev.yosemite.cx.tetrate.info."
#         "external-dns.alpha.kubernetes.io/alias": "true"
#         "external-dns.alpha.kubernetes.io/set-identifier": "aws-east"
#         "external-dns.alpha.kubernetes.io/aws-region": "us-east-2"
#         "service.beta.kubernetes.io/aws-load-balancer-type": "nlb"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontend
spec:
  dnsNames:
  - credit.rh-demo.cx.tetrate.info
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: traffic-generator
# spec:
#   template:
#     spec:
#       containers:
#       - name: trafficgenerator
#         env:
#           - name: URL
#             value: "https://fraud.aws-east-dev.yosemite.cx.tetrate.info/p/http/backend"